### ISSUE TITLE
hello,Why was invise deleted? Very excellent software

### ISSUE THREAD

**Issue by satanmp** [EugeneSunrise/ForzaHorizon4And5FastFix#1]
hello,Why was invise deleted? Very excellent software

**Comment by satanmp** [comment]
> > hello,Why was invise deleted? Very excellent software
> 
> Sup, sold

Was it bought? How much?

**Comment by EugeneSunrise** [comment]
> > > hello,Why was invise deleted? Very excellent software
> 
> > 
> 
> > Sup, sold
> 
> 
> 
> Was it bought? How much?

Yes, not very expensive

**Comment by satanmp** [comment]
> > > > hello,Why was invise deleted? Very excellent software
> > 
> > 
> > > 
> > 
> > 
> > > Sup, sold
> > 
> > 
> > Was it bought? How much?
> 
> Yes, not very expensive


Will you continue to develop it? If you can pass the Facebook account account anti-correlation and some bot detection websites, can I also pay? But I only know how to winform

**Comment by EugeneSunrise** [comment]
> > > > > hello,Why was invise deleted? Very excellent software
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Sup, sold
> 
> > > 
> 
> > > 
> 
> > > Was it bought? How much?
> 
> > 
> 
> > Yes, not very expensive
> 
> 
> 
> 
> 
> Will you continue to develop it? If you can pass the Facebook account account anti-correlation and some bot detection websites, can I also pay? But I only know how to winform

Yep, I’m the main developer, if I don’t forget, I’ll let you know when the product is ready for use
