### ISSUE TITLE
hello,Have you finished invise?

### ISSUE THREAD

**Issue by satanmp** [EugeneSunrise/ForzaHorizon4And5FastFix#2]
hello,Have you finished invise?

**Comment by EugeneSunrise** [comment]
> hello,Have you finished invise?

Hi, I think it would be ready in ~3 weeks

**Comment by satanmp** [comment]
> > hello,Have you finished invise?
> 
> Hi, I think it would be ready in ~3 weeks

Okay, okay, just notify me via email and let me test it out. I can pay you some fees.

**Comment by satanmp** [comment]
Have you finished invise?

**Comment by EugeneSunrise** [comment]
> Have you finished invise?

Doing final tests,release soon, but there is a problem, browser and panel now supports only russian language, english will be added after the release, so I think about a month

**Comment by satanmp** [comment]
Can I get the source code and the final compiled file? If it can pass the detection of facebook and https://www.browserscan.net/bot-detection, I will pay you.

**Comment by EugeneSunrise** [comment]
> Can I get the source code and the final compiled file? If it can pass the detection of facebook and https://www.browserscan.net/bot-detection, I will pay you.

source code - no, final build only after ~month, will check facebook later
![Screenshot 05-05-2024 at 03-41-28](https://github.com/EugeneSunrise/ForzaHorizon4And5FastFix/assets/56397706/226e8c51-ce86-448c-8b9b-2503cb1ec32a)
![Screenshot 05-05-2024 at 03-47-12](https://github.com/EugeneSunrise/ForzaHorizon4And5FastFix/assets/56397706/1ab49977-24f1-4106-b936-514e18667110)
![Screenshot 05-05-2024 at 03-50-36](https://github.com/EugeneSunrise/ForzaHorizon4And5FastFix/assets/56397706/c6beeb4b-8321-47ad-ba62-c535d2f32815)

**Comment by satanmp** [comment]
> > Can I get the source code and the final compiled file? If it can pass the detection of facebook and https://www.browserscan.net/bot-detection, I will pay you.
> 
> source code - no, final build only after ~month, will check facebook later ![Screenshot 05-05-2024 at 03-41-28](https://private-user-images.githubusercontent.com/56397706/327965887-226e8c51-ce86-448c-8b9b-2503cb1ec32a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU4ODctMjI2ZThjNTEtY2U4Ni00NDhjLThiOWItMjUwM2NiMWVjMzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWUyODdmNTlmOWIwZjE2MjA2NjdhMmY0NjRmM2ZjNWU4Y2Q2NmY0OWNjZGZmMGRlNWQ0MTNhMTE1YTNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xR1sxc_OrY51VCN-JnPixZKxwk65y_48g7bA6a_KtZc) ![Screenshot 05-05-2024 at 03-47-12](https://private-user-images.githubusercontent.com/56397706/327965937-1ab49977-24f1-4106-b936-514e18667110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5MzctMWFiNDk5NzctMjRmMS00MTA2LWI5MzYtNTE0ZTE4NjY3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViY2RiMDFkZWU2YzRiMmU0NjA2MjBiNmI5Nzg1Yjc4ZWMyY2E1MjhiNjlhMTM2NmQ3Yzg3MTViNzQ4M2U1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LIEYdNGsqNuavrfA75ZAVjF62OuXb6pTL0SGg_Wktc) ![Screenshot 05-05-2024 at 03-50-36](https://private-user-images.githubusercontent.com/56397706/327965975-c6beeb4b-8321-47ad-ba62-c535d2f32815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5NzUtYzZiZWViNGItODMyMS00N2FkLWJhNjItYzUzNWQyZjMyODE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NWQ2OGJhMjZjNDY5NjNmOGMyYTBlOGI1ZTVhYzBkNTZhNTVjMjg4YmFhZmQwODhkMmYwYTM3NWMzNTA4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWltSLr2TUT-R9Ja7XL5lAlQdcfS3uOewqw8aRubJAA)

I just want the final software to be useless, I want secondary development, otherwise there is no point in paying. There are many such finished software on the market with better results. If you are interested, please contact me. I need the source code.

**Comment by EugeneSunrise** [comment]
> > > Can I get the source code and the final compiled file? If it can pass the detection of facebook and https://www.browserscan.net/bot-detection, I will pay you.
> 
> > 
> 
> > source code - no, final build only after ~month, will check facebook later ![Screenshot 05-05-2024 at 03-41-28](https://private-user-images.githubusercontent.com/56397706/327965887-226e8c51-ce86-448c-8b9b-2503cb1ec32a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU4ODctMjI2ZThjNTEtY2U4Ni00NDhjLThiOWItMjUwM2NiMWVjMzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWUyODdmNTlmOWIwZjE2MjA2NjdhMmY0NjRmM2ZjNWU4Y2Q2NmY0OWNjZGZmMGRlNWQ0MTNhMTE1YTNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xR1sxc_OrY51VCN-JnPixZKxwk65y_48g7bA6a_KtZc) ![Screenshot 05-05-2024 at 03-47-12](https://private-user-images.githubusercontent.com/56397706/327965937-1ab49977-24f1-4106-b936-514e18667110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5MzctMWFiNDk5NzctMjRmMS00MTA2LWI5MzYtNTE0ZTE4NjY3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViY2RiMDFkZWU2YzRiMmU0NjA2MjBiNmI5Nzg1Yjc4ZWMyY2E1MjhiNjlhMTM2NmQ3Yzg3MTViNzQ4M2U1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LIEYdNGsqNuavrfA75ZAVjF62OuXb6pTL0SGg_Wktc) ![Screenshot 05-05-2024 at 03-50-36](https://private-user-images.githubusercontent.com/56397706/327965975-c6beeb4b-8321-47ad-ba62-c535d2f32815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5NzUtYzZiZWViNGItODMyMS00N2FkLWJhNjItYzUzNWQyZjMyODE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NWQ2OGJhMjZjNDY5NjNmOGMyYTBlOGI1ZTVhYzBkNTZhNTVjMjg4YmFhZmQwODhkMmYwYTM3NWMzNTA4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWltSLr2TUT-R9Ja7XL5lAlQdcfS3uOewqw8aRubJAA)
> 
> 
> 
> I just want the final software to be useless, I want secondary development, otherwise there is no point in paying. There are many such finished software on the market with better results. If you are interested, please contact me. I need the source code.

Secondary development will cost 2.5k$ per month

**Comment by satanmp** [comment]
> > > > Can I get the source code and the final compiled file? If it can pass the detection of facebook and https://www.browserscan.net/bot-detection, I will pay you.
> > 
> > 
> > > 
> > 
> > 
> > > source code - no, final build only after ~month, will check facebook later ![Screenshot 05-05-2024 at 03-41-28](https://private-user-images.githubusercontent.com/56397706/327965887-226e8c51-ce86-448c-8b9b-2503cb1ec32a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU4ODctMjI2ZThjNTEtY2U4Ni00NDhjLThiOWItMjUwM2NiMWVjMzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWUyODdmNTlmOWIwZjE2MjA2NjdhMmY0NjRmM2ZjNWU4Y2Q2NmY0OWNjZGZmMGRlNWQ0MTNhMTE1YTNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xR1sxc_OrY51VCN-JnPixZKxwk65y_48g7bA6a_KtZc) ![Screenshot 05-05-2024 at 03-47-12](https://private-user-images.githubusercontent.com/56397706/327965937-1ab49977-24f1-4106-b936-514e18667110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5MzctMWFiNDk5NzctMjRmMS00MTA2LWI5MzYtNTE0ZTE4NjY3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViY2RiMDFkZWU2YzRiMmU0NjA2MjBiNmI5Nzg1Yjc4ZWMyY2E1MjhiNjlhMTM2NmQ3Yzg3MTViNzQ4M2U1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LIEYdNGsqNuavrfA75ZAVjF62OuXb6pTL0SGg_Wktc) ![Screenshot 05-05-2024 at 03-50-36](https://private-user-images.githubusercontent.com/56397706/327965975-c6beeb4b-8321-47ad-ba62-c535d2f32815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5NzUtYzZiZWViNGItODMyMS00N2FkLWJhNjItYzUzNWQyZjMyODE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NWQ2OGJhMjZjNDY5NjNmOGMyYTBlOGI1ZTVhYzBkNTZhNTVjMjg4YmFhZmQwODhkMmYwYTM3NWMzNTA4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWltSLr2TUT-R9Ja7XL5lAlQdcfS3uOewqw8aRubJAA)
> > 
> > 
> > I just want the final software to be useless, I want secondary development, otherwise there is no point in paying. There are many such finished software on the market with better results. If you are interested, please contact me. I need the source code.
> 
> Secondary development will cost 2.5k$ per month

200$ for ever,otherwise,please close this issue

**Comment by satanmp** [comment]
> > > > Can I get the source code and the final compiled file? If it can pass the detection of facebook and https://www.browserscan.net/bot-detection, I will pay you.
> > 
> > 
> > > 
> > 
> > 
> > > source code - no, final build only after ~month, will check facebook later ![Screenshot 05-05-2024 at 03-41-28](https://private-user-images.githubusercontent.com/56397706/327965887-226e8c51-ce86-448c-8b9b-2503cb1ec32a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU4ODctMjI2ZThjNTEtY2U4Ni00NDhjLThiOWItMjUwM2NiMWVjMzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWUyODdmNTlmOWIwZjE2MjA2NjdhMmY0NjRmM2ZjNWU4Y2Q2NmY0OWNjZGZmMGRlNWQ0MTNhMTE1YTNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xR1sxc_OrY51VCN-JnPixZKxwk65y_48g7bA6a_KtZc) ![Screenshot 05-05-2024 at 03-47-12](https://private-user-images.githubusercontent.com/56397706/327965937-1ab49977-24f1-4106-b936-514e18667110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5MzctMWFiNDk5NzctMjRmMS00MTA2LWI5MzYtNTE0ZTE4NjY3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViY2RiMDFkZWU2YzRiMmU0NjA2MjBiNmI5Nzg1Yjc4ZWMyY2E1MjhiNjlhMTM2NmQ3Yzg3MTViNzQ4M2U1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LIEYdNGsqNuavrfA75ZAVjF62OuXb6pTL0SGg_Wktc) ![Screenshot 05-05-2024 at 03-50-36](https://private-user-images.githubusercontent.com/56397706/327965975-c6beeb4b-8321-47ad-ba62-c535d2f32815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5NzUtYzZiZWViNGItODMyMS00N2FkLWJhNjItYzUzNWQyZjMyODE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NWQ2OGJhMjZjNDY5NjNmOGMyYTBlOGI1ZTVhYzBkNTZhNTVjMjg4YmFhZmQwODhkMmYwYTM3NWMzNTA4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWltSLr2TUT-R9Ja7XL5lAlQdcfS3uOewqw8aRubJAA)
> > 
> > 
> > I just want the final software to be useless, I want secondary development, otherwise there is no point in paying. There are many such finished software on the market with better results. If you are interested, please contact me. I need the source code.
> 
> Secondary development will cost 2.5k$ per month

please send me source code via email,I want to test it.

**Comment by satanmp** [comment]
> > > > Can I get the source code and the final compiled file? If it can pass the detection of facebook and https://www.browserscan.net/bot-detection, I will pay you.
> > 
> > 
> > > 
> > 
> > 
> > > source code - no, final build only after ~month, will check facebook later ![Screenshot 05-05-2024 at 03-41-28](https://private-user-images.githubusercontent.com/56397706/327965887-226e8c51-ce86-448c-8b9b-2503cb1ec32a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU4ODctMjI2ZThjNTEtY2U4Ni00NDhjLThiOWItMjUwM2NiMWVjMzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWUyODdmNTlmOWIwZjE2MjA2NjdhMmY0NjRmM2ZjNWU4Y2Q2NmY0OWNjZGZmMGRlNWQ0MTNhMTE1YTNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xR1sxc_OrY51VCN-JnPixZKxwk65y_48g7bA6a_KtZc) ![Screenshot 05-05-2024 at 03-47-12](https://private-user-images.githubusercontent.com/56397706/327965937-1ab49977-24f1-4106-b936-514e18667110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5MzctMWFiNDk5NzctMjRmMS00MTA2LWI5MzYtNTE0ZTE4NjY3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViY2RiMDFkZWU2YzRiMmU0NjA2MjBiNmI5Nzg1Yjc4ZWMyY2E1MjhiNjlhMTM2NmQ3Yzg3MTViNzQ4M2U1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LIEYdNGsqNuavrfA75ZAVjF62OuXb6pTL0SGg_Wktc) ![Screenshot 05-05-2024 at 03-50-36](https://private-user-images.githubusercontent.com/56397706/327965975-c6beeb4b-8321-47ad-ba62-c535d2f32815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjM0NDAsIm5iZiI6MTcxNDg2MzE0MCwicGF0aCI6Ii81NjM5NzcwNi8zMjc5NjU5NzUtYzZiZWViNGItODMyMS00N2FkLWJhNjItYzUzNWQyZjMyODE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NWQ2OGJhMjZjNDY5NjNmOGMyYTBlOGI1ZTVhYzBkNTZhNTVjMjg4YmFhZmQwODhkMmYwYTM3NWMzNTA4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWltSLr2TUT-R9Ja7XL5lAlQdcfS3uOewqw8aRubJAA)
> > 
> > 
> > I just want the final software to be useless, I want secondary development, otherwise there is no point in paying. There are many such finished software on the market with better results. If you are interested, please contact me. I need the source code.
> 
> Secondary development will cost 2.5k$ per month

200$ for ever,if you agree，There are too many of these products, and you won’t make much money selling them.
